package com.match3.game.domain.model

sealed class GameEvent {
    data class BlocksSwapped(val pos1: Position, val pos2: Position) : GameEvent()
    data class BlocksMatched(val positions: Set<Position>, val color: BlockColor) : GameEvent()
    data class BlocksDestroyed(val positions: Set<Position>) : GameEvent()
    data class BlocksFell(val movements: List<Pair<Position, Position>>) : GameEvent()
    data class BlocksSpawned(val positions: List<Position>) : GameEvent()
    data class SpecialCreated(val position: Position, val type: SpecialType, val color: BlockColor) : GameEvent()
    data class SpecialActivated(val position: Position, val type: SpecialType) : GameEvent()
    data class RocketFired(val position: Position, val isHorizontal: Boolean, val clearedPositions: Set<Position>) : GameEvent()
    data class BombExploded(val position: Position, val clearedPositions: Set<Position>) : GameEvent()
    data class PropellerFlew(val from: Position, val to: Position, val clearedPositions: Set<Position>) : GameEvent()
    data class PropellerCarrying(val from: Position, val to: Position, val carryingType: SpecialType) : GameEvent()
    data class DiscoActivated(val position: Position, val color: BlockColor, val clearedPositions: Set<Position>) : GameEvent()
    data class ComboActivated(val type1: SpecialType, val type2: SpecialType, val position: Position) : GameEvent()
    data class ScoreGained(val points: Int, val position: Position, val multiplier: Float) : GameEvent()
    data class CellDamaged(val position: Position, val newDurability: Int) : GameEvent()
    data class CellCleared(val position: Position, val type: CellType) : GameEvent()
    data class ProjectileFired(val fromCol: Int, val damage: Int) : GameEvent()
    data class EnemyDamaged(val enemyId: Int, val damage: Int, val remainingHp: Int) : GameEvent()
    data class EnemyDestroyed(val enemyId: Int, val position: Position) : GameEvent()
    data class GateDamaged(val damage: Int, val remainingDurability: Int) : GameEvent()
    data class TurnEnded(val turnsRemaining: Int) : GameEvent()
    data class CascadeStarted(val level: Int) : GameEvent()
    data class CascadeEnded(val totalMatches: Int) : GameEvent()
    object BoardStabilized : GameEvent()
    data class GameWon(val score: Int, val bonusCurrency: Int) : GameEvent()
    data class GameLost(val reason: String) : GameEvent()
}
